

$(document).ready(function() {
    $("#unique").click(function() {
        if($('#unique:checked').length) {
            $("#randomize3").show(300);
        } else {
            $("#randomize3").hide(300);
        }
    });

    $("#keystone").click(function() {
        if($('#keystone:checked').length) {
            $("#randomize4").show(300);
        } else {
            $("#randomize4").hide(300);
        }
    });
    $("#skill").click(function() {
        if($('#skill:checked').length) {
            $("#randomize2").show(300);
        } else {
            $("#randomize2").hide(300);
        }
    });
})

function randomizeIt(theArray, howMany) {
    var upperBound = theArray.length;
    var returnValue = "";
    for(i = 0; i < howMany; i++) {
        var theChoice = Math.floor((Math.random() * upperBound) + 1);
        returnValue += (theArray[theChoice-1]);
        if (i != (howMany - 1)) {
            returnValue += ", "
        };
    };
    return returnValue;
};


function Randomize() {
    document.getElementById("randomize1").innerHTML = "Class: " + randomizeIt(classes, 1);
    var SkillNum = document.getElementById("skillnum").value;
    document.getElementById("randomize2").innerHTML = "Skill: " + randomizeIt(skills, SkillNum);
    var UniqueNum = document.getElementById("uniquenum").value;
    document.getElementById("randomize3").innerHTML = "Unique(s): "+randomizeIt(uniques, UniqueNum);
    var KeystoneNum = document.getElementById("keystonenum").value;
    document.getElementById("randomize4").innerHTML = "Keystone(s): " + randomizeIt(keystones, KeystoneNum);
}

var classes = ['Slayer',
'Gladiator',
'Champion',
'Assassin',
'Saboteur',
'Trickster',
'Juggernaut',
'Berserker',
'Chieftain',
'Nercromancer',
'Elementalist',
'Occultist',
'Deadeye',
'Raider',
'Pathfinder',
'Inquisitor',
'Hierophant',
'Guardian',
'Ascendent',]

var skills = ['Kinetic Bolt',
'Spellslinger Chaos',
'Spellslinger Physical',
'Spellslinger Cold',
'Spellslinger Fire',
'Spellslinger Lightning',
'Generals Cry',
'Penance Brand',
'Wintertide Brand',
'Arcanist Brand',
'Earthshatter',
'Spellslinger Any',
'Stormbind',
'Blade Blast',
'Ancestral Protector',
'Ancestral Warchief',
'Animate Guardian',
'Animate Weapon',
'Arc',
'Arctic Breath',
'Armageddon Brand',
'Ball Lightning',
'Bane',
'Barrage',
'Bear Trap',
'Blade Flurry',
'Blade Storm',
'Blade Vortex',
'Bladefall',
'Blast Rain',
'Blight',
'Burning Arrow',
'Caustic Arrow',
'Charged Dash',
'Cleave',
'Cobra Lash',
'Cold Snap',
'Consecrated Path',
'Contagion',
'Cremation',
'Cyclone',
'Dark Pact',
'Detonate Dead',
'Discharge',
'Divine Ire',
'Dominating Blow',
'Double Strike',
'Dual Strike',
'Earthquake',
'Elemental Hit',
'Essence Drain',
'Ethereal Knives',
'Explosive Arrow',
'Explosive Trap',
'Pyroclast Mine',
'Icicle Mine',
'Fire Trap',
'Fireball',
'Firestorm',
'Flame Dash',
'Flame Surge',
'Flame Totem',
'Flameblast',
'Flamethrower Trap',
'Flicker Strike',
'Freezing Pulse',
'Frenzy',
'Frost Blades',
'Frost Bomb',
'Frostbolt',
'Glacial Cascade',
'Glacial Hammer',
'Ground Slam',
'Heavy Strike',
'Ice Crash',
'Ice Nova',
'Ice Shot',
'Ice Spear',
'Ice Trap',
'Incinerate',
'Infernal Blow',
'Kinetic Blast',
'Lacerate',
'Lancing Steel',
'Leap Slam',
'Lightning Arrow',
'Lightning Spire Trap',
'Lightning Strike',
'Lightning Tendrils',
'Lightning Trap',
'Lightning Warp',
'Magma Orb',
'Molten Strike',
'Orb of Storms',
'Perforate',
'Pestilent Strike',
'Power Siphon',
'Puncture',
'Purifying Flame',
'Rain of Arrows',
'Raise Spectre',
'Raise Zombie',
'Reave',
'Reckoning',
'Righteous Fire',
'Riposte',
'Scorching Ray',
'Scourge Arrow',
'Searing Bond',
'Seismic Trap',
'Shattering Steel',
'Shield Charge',
'Shock Nova',
'Shockwave Totem',
'Shrapnel Shot',
'Siege Ballista',
'Siphoning Trap',
'Smite',
'Soul Rend',
'Spark',
'Spectral Shield Throw',
'Spectral Throw',
'Split Arrow',
'Static Strike',
'Storm Brand',
'Storm Burst',
'Storm Call',
'Stormblast Mine',
'Summon Carrion Golem',
'Summon Chaos Golem',
'Summon Flame Golem',
'Summon Holy Relic',
'Summon Ice Golem',
'Summon Lightning Golem',
'Summon Raging Spirit',
'Summon Skeleton',
'Summon Stone Golem',
'Sunder',
'Sweep',
'Tectonic Slam',
'Tornado Shot',
'Toxic Rain',
'Vengeance',
'Venom Gyre',
'Vigilant Strike',
'Viper Strike',
'Volatile Dead',
'Vortex',
'Wave Of Conviction',
'Wild Strike',
'Winter Orb',]

var uniques = [
'Abhorrent Interrogation',
'Bears Girdle',
'Doryanis Prototype',
'Emperors Vigilance',
'Fleshcrafter',
'Forbidden Shako',
'Great Old Ones Tentacles',
'Infused Beachhead',
'Law of the Wilds',
'Plume of Pursuit',
'Retaliation Charm',
'Scorpions Call',
'Storm Secret',
'The Felbog Fang',
'The Immortal Will',
'The Shattered Divinity',
'The Surging Thoughts',
'The Tempests Liberation',
'The Torrents Reclamation',
'The Yielding Mortality',
'Witchhunters Judgment',
'Algor Mortis',
'Assailum',
'Beacon of Madness',
'Calamitous Visions',
'Kitavas Teachings',
'Megalomaniac',
'Natural Affinity',
'One With Nothing',
'Perfidy',
'Profane Proxy',
'Split Personality',
'The Front Line',
'The Interrogation',
'The Siege',
'Voices',
'Lycosidae',
'Trolltimber Spire',
'Titucius Span',
'Redblade Banner',
'Chernobogs Pillar',
'Tukohamas Fortress',
'The Surrender',
'The Anticipation',
'Ahns Heritage',
'Lioneyes Remorse',
'Magna Eclipsis',
'Crest of Perandus',
'Kaltenhalt',
'Kaltensoul',
'Chalice of Horrors',
'Thirst for Horrors',
'Mutewind Pennant',
'Great Old Ones Ward',
'Atziris Mirror',
'Atziris Reflection',
'Thousand Teeth Temu',
'Matua Tupuna',
'Brinerot Flag',
'Light of Lunaris',
'Sentaris Answer',
'Kongmings Stratagem',
'Apeps Slumber',
'The Eternal Apple',
'Eshs Mirror',
'Eshs Visage',
'Apeps Supremacy',
'Malachais Loop',
'Rathpith Globe',
'Wheel of the Stormsail',
'The Deep Ones Hide',
'Daressos Courage',
'Vix Lunaris',
'Springleaf',
'The Oak',
'Victarios Charity',
'Saffells Frame',
'Aegis Aurora',
'Rise of the Phoenix',
'Prism Guardian',
'Broken Faith',
'The Unshattered Will',
'Invictus Solaris',
'Unyielding Flame',
'Glitterdisc',
'Maligaros Lens',
'Zeels Amplifier',
'Lepers Alms',
'Jaws of Agony',
'Ezomyte Peak',
'Ezomyte Hold',
'The Baron',
'The Formless Flame',
'Hrimnors Resolve',
'Abyssus',
'The Formless Inferno',
'Goldrim',
'Fairgraves Tricorne',
'Heatshiver',
'Frostferno',
'Rats Nest',
'Starkonjas Head',
'Saqawals Flock',
'Alphas Howl',
'Obscurantis',
'Crown of Thorns',
'Martyrs Crown',
'Asenaths Mark',
'Asenaths Chant',
'Mark of the Red Covenant',
'Wraithlord',
'Doedres Scorn',
'Chitus Apex',
'Fenumus Toxins',
'Rime Gaze',
'Scolds Bridle',
'Hale Negator',
'Crown of Eyes',
'Ylfebans Trickery',
'Ebers Unification',
'Indigon',
'The Peregrine',
'Deidbell',
'Deidbellow',
'Skullhead',
'Black Sun Crest',
'The Bringer of Rain',
'Devotos Devotion',
'Honourhome',
'Veil of the Night',
'Mask of the Spirit Drinker',
'Mindspiral',
'Kitavas Thirst',
'Geofris Crest',
'Lightpoacher',
'Geofris Legacy',
'Craiceanns Chitin',
'Mask of the Stitched Demon',
'Crown of the Tyrant',
'The Broken Crown',
'The Brine Crown',
'Speakers Wreath',
'Volls Vision',
'Malachais Vision',
'Ahns Contempt',
'Memory Vault',
'Curtain Call',
'Malachais Simula',
'Malachais Awakening',
'Leer Cast',
'The Three Dragons',
'The Gull',
'The Tempests Binding',
'Crown of the Pale King',
'Gorgons Gaze',
'Mind of the Council',
'Farruls Bite',
'The Vertex',
'Heretics Veil',
'Bramblejack',
'Wall of Brambles',
'Skin of the Loyal',
'Solaris Lorica',
'Greeds Embrace',
'Craiceanns Carapace',
'Lioneyes Vision',
'Iron Heart',
'The Iron Fortress',
'Deaths Oath',
'The Brass Dome',
'Kaoms Heart',
'Briskwrap',
'Wildwrap',
'Ashrend',
'Foxshade',
'Foxs Fortune',
'The Snowblind Grace',
'Bronns Lithe',
'The Rat Cage',
'Queen of the Forest',
'Kintsugi',
'Yriels Fostering',
'Hyrris Ire',
'The Perfect Form',
'Cospris Will',
'Thousand Ribbons',
'Skin of the Lords',
'Cloak of Flame',
'Zahndethus Cassock',
'Diallas Malefaction',
'The Covenant',
'Soul Mantle',
'The Coming Calamity',
'Cloak of Tawmr Isley',
'Vis Mortis',
'Shavronnes Wrappings',
'Infernal Mantle',
'Doedres Skin',
'Fenumus Shroud',
'The Beast Fur Shawl',
'Vipers Scales',
'Gruthkuls Pelt',
'Belly of the Beast',
'Lightning Coil',
'Daressos Defiance',
'Cherrubims Maleficence',
'Farruls Fur',
'Volls Protector',
'Icetomb',
'Crystal Vault',
'Ambus Charge',
'Lightbane Raiment',
'Kingsguard',
'Geofris Sanctuary',
'Loreweave',
'Incandescent Heart',
'Chains of Command',
'Bloodbond',
'Cloak of Defiance',
'Victarios Influence',
'Dendrobate',
'Carcass Jack',
'Saqawals Nest',
'Tinkerskin',
'Inpulsas Broken Heart',
'The Restless Ward',
'Shroud of the Lightless',
'Atziris Splendour',
'Shadowstitch',
'Demigods Dominance',
'Stormcharger',
'Windscream',
'Windshriek',
'Redblade Tramplers',
'The Infinite Pursuit',
'Craiceanns Tracks',
'Kaoms Roots',
'The Red Trail',
'Seven-League Step',
'Victarios Flight',
'Abberaths Hooves',
'Deerstalker',
'Goldwyrm',
'The Blood Dance',
'Three-step Assault',
'Sin Trek',
'Garukhans Flight',
'Atziris Step',
'Farruls Chase',
'Wanderlust',
'Wondertrap',
'Greedtrap',
'Bones of Ullr',
'Shavronnes Pace',
'Shavronnes Gambit',
'Rainbowstride',
'Inyas Epiphany',
'Steppan Eard',
'Skyforth',
'Dusktoe',
'Duskblight',
'Lioneyes Paws',
'Mutewind Whispersteps',
'Saqawals Talons',
'Darkray Vectors',
'Wake of Destruction',
'Ralakeshs Impatience',
'Alberons Warpath',
'Gangs Momentum',
'Deaths Door',
'Nomics Storm',
'Sundance',
'Sunspite',
'Dance of the Offered',
'Brinerot Whalers',
'Omeyocan',
'Fenumus Spinnerets',
'Voidwalker',
'Bubonic Trail',
'Lochtonial Caress',
'Giantsbane',
'Meginords Vise',
'Winds of Change',
'Empires Grasp',
'Atziris Acuity',
'Doryanis Fist',
'Verusos Battering Rams',
'Craiceanns Pincers',
'Hrimsorrow',
'Hrimburn',
'Maligaros Virtuosity',
'Oskarm',
'Sadimas Touch',
'Doedres Tenure',
'Doedres Malevolence',
'Asenaths Gentle Touch',
'Demon Stitcher',
'Kalisas Grace',
'Voidbringer',
'Grip of the Council',
'Allelopathy',
'Flesh and Spirit',
'Slitherpinch',
'Vaal Caress',
'Aurseize',
'Tombfist',
'Haemophilia',
'Wyrmsign',
'Farruls Pounce',
'Surgebinders',
'Shackles of the Wretched',
'Command of the Pit',
'Volkuurs Guidance',
'Southbound',
'Saqawals Winds',
'Null and Void',
'Repentance',
'Shapers Touch',
'Ondars Clasp',
'Facebreaker',
'Architects Hand',
'Shadows and Dust',
'Slavedrivers Hand',
'The Embalmer',
'Fenumus Weave',
'Snakebite',
'Blasphemers Grasp',
'Thunderfist',
'Malachais Mark',
'Lifesprig',
'Abberaths Horn',
'Storm Prison',
'The Poets Pen',
'Ashcaller',
'Reverberation Rod',
'Amplification Rod',
'Tulborn',
'Twyzel',
'Shade of Solaris',
'Midnight Bargain',
'Eclipse Solaris',
'Corona Solaris',
'Obliteration',
'Moonsorrow',
'Apeps Rage',
'Piscators Vigil',
'Tulfall',
'Shimmeron',
'Void Battery',
'Goredrill',
'Sanguine Gambol',
'Bloodplay',
'Ungils Gauche',
'Mightflay',
'Widowmaker',
'Heartbreaker',
'The Consuming Dark',
'Arakaalis Fang',
'Binos Kitchen Knife',
'Taproot',
'Mark of the Doubting Knight',
'Divinarius',
'White Wind',
'Vulconus',
'Last Resort',
'Wildslash',
'Hand of Thought and Motion',
'Al Dhih',
'Mortem Morsu',
'Cybils Paw',
'Ornament of the East',
'Advancing Fortress',
'The Wasp Nest',
'Bloodseeker',
'Essentia Sanguis',
'Allure',
'Izaros Dilemma',
'Touch of Anguish',
'Hand of Wisdom and Action',
'Rive',
'The Scourge',
'The Screaming Eagle',
'The Gryphon',
'Dreadarc',
'Dreadsurge',
'Relentless Fury',
'Moonbenders Wing',
'Soul Taker',
'Jack, the Axe',
'Rigwalds Savagery',
'Dyadus',
'Oni-Goroshi',
'Redbeak',
'Dreadbeak',
'The Princess',
'The Tempestuous Steel',
'The Goddess Scorned',
'Lakishus Blade',
'Ephemeral Edge',
'Story of the Vaal',
'Severed in Sleep',
'United in Dream',
'Innsbury Edge',
'Prismatic Eclipse',
'Fate of the Vaal',
'Ichimonji',
'Scaeva',
'Hyaons Fury',
'The Rippling Thoughts',
'Rebuke of the Vaal',
'Varunastra',
'Dreamfeather',
'The Goddess Unleashed',
'Beltimber Blade',
'Grelwood Shank',
'Rigwalds Command',
'Razor of the Seventh Sun',
'Ahns Might',
'The Goddess Bound',
'Aurumvorax',
'Fidelitas Spike',
'Ewars Mirage',
'Chitus Needle',
'Daressos Passion',
'Cospris Malice',
'Gorebreaker',
'Brightbeak',
'Laviangas Wisdom',
'Flesh-Eater',
'Clayshaper',
'Frostbreath',
'Mjölner',
'Camerias Maul',
'Camerias Avarice',
'Callinellus Malleus',
'Nebuloch',
'Axiom Perpetuum',
'Spine of the First Claimant',
'Brutus Lead Sprinkler',
'The Dark Seer',
'Bitterdream',
'Earendels Embrace',
'Nyctas Lantern',
'The Supreme Truth',
'Cerberus Limb',
'Deaths Hand',
'Balefire',
'Singularity',
'Doon Cuebiyari',
'Doryanis Catalyst',
'Breath of the Council',
'Montreguls Grasp',
'Augyre',
'Silverbranch',
'Silverbough',
'Quill Rain',
'Storm Cloud',
'The Tempest',
'Roths Reach',
'Xophs Inception',
'Doomfletch',
'Doomfletchs Prism',
'Deaths Harp',
'Iron Commander',
'Deaths Opus',
'Infractem',
'Xophs Nurture',
'Nulls Inclination',
'Hopeshredder',
'Chin Sol',
'Arborix',
'Voltaxic Rift',
'Reach of the Council',
'Lioneyes Glare',
'Windripper',
'Nuros Harp',
'Slivertongue',
'Darkscorn',
'Fencoil',
'The Blood Thorn',
'Mirebough',
'Pillar of the Caged God',
'Dying Breath',
'Realmshaper',
'Realm Ender',
'Xirgils Crank',
'The Stormheart',
'The Stormwall',
'The Whispering Ice',
'Tremor Rod',
'Sire of Shards',
'Martyr of Innocence',
'Femurs of the Saints',
'The Searing Touch',
'Cane of Unravelling',
'Soulwrest',
'Taryns Shiver',
'Duskdawn',
'Disintegrator',
'Agnerod East',
'Agnerod North',
'Agnerod South',
'Agnerod West',
'The Enmity Divine',
'Pledge of Hands',
'Hegemonys Era',
'The Grey Spire',
'Limbsplit',
'The Cauteriser',
'Wideswing',
'Reapers Pursuit',
'The Harvest',
'The Blood Reaper',
'Uul-Netols Kiss',
'Ngamahus Flame',
'Kaoms Primacy',
'Wings of Entropy',
'Sinvictas Mettle',
'Atziris Disfavour',
'Hezmanas Bloodlust',
'Uul-Netols Embrace',
'Kingmaker',
'Debeons Dirge',
'Kitavas Feast',
'Shiversting',
'Edge of Madness',
'Queens Decree',
'Queens Escape',
'Rigwalds Charge',
'Terminus Est',
'The Dancing Dervish',
'Hiltless',
'The Dancing Duo',
'Kondos Pride',
'Doomsower',
'Oros Sacrifice',
'Starforge',
'Voidforge',
'Hrimnors Hymn',
'Hrimnors Dirge',
'Quecholli',
'Panquetzaliztli',
'Geofris Baptism',
'Geofris Devotion',
'Chober Chaber',
'Trypanon',
'Chaber Cairn',
'Jorrhasts Blacksteel',
'Voidhome',
'Marohi Erqi',
'Brain Rattler',
'Tidebreaker',
'Kongors Undying Rage',
'Song of the Sirens',
'Reefbane',
'Blackheart',
'Le Heup of All',
'Voidheart',
'The Wardens Brand',
'Kaoms Sign',
'Bloodboil',
'Sibyls Lament',
'Kaoms Way',
'Winterweave',
'Doedres Damning',
'Perandus Signet',
'Praxis',
'Andvarius',
'Ventors Gamble',
'Kikazaru',
'Valakos Sign',
'Putembos Valley',
'Putembos Mountain',
'Putembos Meadow',
'Precursors Emblem',
'Dream Fragments',
'Pyre',
'Tasalios Sign',
'Snakepit',
'Uzazas Meadow',
'Uzazas Mountain',
'Uzazas Valley',
'Mokous Embrace',
'Ngamahus Sign',
'Emberwake',
'Ahkelis Mountain',
'Ahkelis Meadow',
'Ahkelis Valley',
'Loris Lantern',
'The Taming',
'Thiefs Torment',
'Shavronnes Revelation',
'Timeclasp',
'Heartbound Loop',
'Valyrium',
'Timetwist',
'Death Rush',
'Mings Heart',
'Gifts from Above',
'Romiras Banquet',
'Bereks Grip',
'Bereks Pass',
'Bereks Respite',
'Call of the Brotherhood',
'Rigwalds Crest',
'Voideye',
'Malachais Artifice',
'Brinerot Mark',
'Redblade Band',
'Mutewind Seal',
'The Pariah',
'Essence Worm',
'Anglers Plait',
'The Hungry Loop',
'Mark of Submission',
'Mark of the Elder',
'Stormfire',
'Mark of the Shaper',
'Atziris Foible',
'Sidhebreath',
'Zerphis Heart',
'Sacrificial Heart',
'Araku Tiki',
'Ngamahu Tiki',
'The Primordial Chain',
'The Anvil',
'Blood of Corruption',
'Xophs Heart',
'Xophs Blood',
'Karui Ward',
'Rashkaldors Patience',
'Karui Charge',
'The Halcyon',
'The Pandemonius',
'Marylenes Fallacy',
'Stone of Lazhwar',
'Tear of Purity',
'Voice of the Storm',
'Choir of the Storm',
'The Ignomon',
'Winterheart',
'The Ascetic',
'Biscos Collar',
'The Effigon',
'Perquils Toe',
'Astramentis',
'Carnage Heart',
'Eye of Chayula',
'Hinekoras Sight',
'Presence of Chayula',
'Yoke of Suffering',
'Impresence',
'Auls Uprising',
'Victarios Acuity',
'Ungils Harmony',
'Warped Timepiece',
'Maligaros Cruelty',
'Volls Devotion',
'Shapers Seed',
'The Aylardex',
'Extractor Mentis',
'Daressos Salute',
'Eye of Innocence',
'Star of Wraeclast',
'Talisman of the Victor',
'Gloomfang',
'Nights Hold',
'Rigwalds Curse',
'Blightwell',
'Natural Hierarchy',
'Eyes of the Greatwolf',
'Prismweave',
'Feastbind',
'Faminebind',
'The Retch',
'Bated Breath',
'Maligaros Restraint',
'Ascent From Flesh',
'Cowards Chains',
'Cowards Legacy',
'Headhunter',
'Immortal Flesh',
'Wurms Molt',
'Umbilicus Immortalis',
'Cyclopean Coil',
'Gluttony',
'Doryanis Invitation',
'Meginords Girdle',
'Belt of the Deceiver',
'Dyadian Dawn',
'Biscos Leash',
'String of Servitude',
'Perandus Blazon',
'Sunblast',
'Soul Tether',
'The Flow Untethered',
'The Magnate',
'Ryslathas Coil',
'The Tactician',
'The Nomad',
'Perseverance',
'Auxium',
'Darkness Enthroned',
'Blood of the Karui',
'Doedres Elixir',
'Zerphis Last Breath',
'Laviangas Spirit',
'Divination Distillate',
'The Writhing Jar',
'Coralitos Signature',
'Coruscating Elixir',
'Dying Sun',
'Taste of Hate',
'Vessel of Vinktar',
'Rumis Concoction',
'Lions Roar',
'Rotgut',
'Atziris Promise',
'Forbidden Taste',
'Soul Catcher',
'Soul Ripper',
'Witchfire Brew',
'Sins Rebirth',
'The Sorrow of the Divine',
'The Overflowing Chalice',
'Kiaras Determination',
'The Wise Oak',
'The Signal Fire',
'Broadstroke',
'Craghead',
'Cragfall',
'Asphyxias Wrath',
'Rigwalds Quills',
'Skirmish',
'Hyrris Bite',
'Hyrris Demise',
'Maloneys Nightfall',
'The Fracturing Spinner',
'Blackgleam',
'Rearguard',
'Drillneck',
'Voidfletcher',
'Soul Strike',
'Saemus Gift',
'Brawn',
'Inertia',
'Survival Skills',
'Inspired Learning',
'Martial Artistry',
'Spire of Stone',
'Mantra of Flames',
'Combustibles',
'Fragile Bloom',
'Rain of Splinters',
'Efficient Training',
'Atziris Reign',
'Blood Sacrifice',
'Warlords Reach',
'Conquerors Efficiency',
'Ancient Waystones',
'Fragility',
'Fireborn',
'Energised Armour',
'Might in All Forms',
'Izaros Turmoil',
'The Vigil',
'Rapid Expansion',
'Shattered Chains',
'Weight of the Empire',
'Emperors Might',
'Grand Spectrum',
'Coated Shrapnel',
'Primordial Might',
'The Red Dream',
'The Red Nightmare',
'Winter Burial',
'Wildfire',
'Overwhelming Odds',
'Might of the Meek',
'Tempered Flesh',
'Combat Focus',
'Transcendent Flesh',
'Fluid Motion',
'Intuitive Leap',
'Lioneyes Fall',
'Survival Instincts',
'Apparitions',
'Hotfooted',
'Weight of Sin',
'Careful Planning',
'Hidden Potential',
'Sacrificial Harvest',
'Self-Flagellation',
'Poachers Aim',
'Conquerors Longevity',
'Chill of Corruption',
'Hungry Abyss',
'Pacifism',
'Pugilist',
'Cold Steel',
'Static Electricity',
'Volley Fire',
'Spirit Guards',
'Pitch Darkness',
'Steel Spirit',
'Growing Agony',
'Cheap Construction',
'Hair Trigger',
'Emperors Cunning',
'Primordial Eminence',
'The Green Dream',
'The Green Nightmare',
'Sudden Ignition',
'Ring of Blades',
'Fight for Survival',
'Omen on the Winds',
'Might and Influence',
'Collateral Damage',
'Pure Talent',
'The Golden Rule',
'Tempered Spirit',
'Transcendent Spirit',
'Unnatural Instinct',
'To Dust',
'Eldritch Knowledge',
'Survival Secrets',
'Fertile Mind',
'Fortified Legion',
'Malicious Intent',
'Clear Mind',
'Brute Force Solution',
'Vaal Sentencing',
'Fevered Mind',
'Powerlessness',
'Assassins Haste',
'Conquerors Potency',
'Mutated Growth',
'Corrupted Energy',
'Brittle Barrier',
'Anatomical Knowledge',
'Energy From Within',
'Healthy Mind',
'Rolling Flames',
'Winters Bounty',
'Spirited Response',
'Dead Reckoning',
'Reckless Defence',
'Unstable Payload',
'Emperors Wit',
'Unending Hunger',
'Primordial Harmony',
'The Blue Dream',
'The Blue Nightmare',
'Violent Dead',
'First Snow',
'Frozen Trail',
'Inevitability',
'Spreading Rot',
'Hazardous Research',
'From Dust',
'The Long Winter',
'Souls Wick',
'Tempered Mind',
'Transcendent Mind',
'Emperors Mastery',
'The Anima Stone',
'Watchers Eye',
'Chris Wilsons Magnificent Beard',
'Bitterbind Point',
'Cinderswallow Urn',
'Flamesight',
'Galesight',
'Hyperboreus',
'Paradoxica',
'Solstice Vigil',
'The Crimson Storm',
'The Devouring Diadem',
'The Queens Hunger',
'Thundersight',
'Vivinsect',
'Whakatutuki o Matua',
'Worldcarver',
'Hyrris Truth',
'Maloneys Mechanism',
'March of the Legion',
'The Eternity Shroud',
'Vixens Entrapment',
'Bottled Faith',
'Wreath of Phrecia',
'Sign of the Sin Eater',
'Tavukai',
'Maw of Conquest',
'Lethal Pride',
'Divide and Conquer',
'Aukunas Will',
'Brutal Restraint',
'Elegant Hubris',
'Fractal Thoughts',
'Glorious Vanity',
'Militant Faith',
'Badge of the Brotherhood',
'Breathstealer',
'Cold Iron Point',
'Cowl of the Ceraunophile',
'Cowl of the Cryophile',
'Cowl of the Thermophile',
'Fortress Covenant',
'Icefang Orbit',
'Machina Mitts',
'Quickening Covenant',
'Rotting Legion',
'Siegebreaker',
'Sporeguard',
'The Jinxed Juju',
'The Stampede',
'Torchoak Step',
'Triad Grip',
'Venopuncture',]

var keystones = ['Acrobatics',
'Ancestral Bond',
'The Agnostic',
'Glancing Blows',
'Eternal Youth',
'Wind Dancer',
'Supreme Ego',
'The Impaler',
'Imbalanced Guard',
'Call to Arms',
'Arrow Dancing',
'Avatar of Fire',
'Blood Magic',
'Chaos Inoculation',
'Crimson Dance',
'Eldritch Battery',
'Elemental Equilibrium',
'Elemental Overload',
'Ghost Reaver',
'Iron Grip',
'Iron Reflexes',
'Mind Over Matter',
'Minion Instability',
'Necromantic Aegis',
'Pain Attunement',
'Perfect Agony',
'Phase Acrobatics',
'Point Blank',
'Resolute Technique',
'Runebinder',
'Unwavering Stance',
'Vaal Pact',
'Wicked Ward',
'Zealots Oath',]